# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    consejo_user_provider:
        class: AppBundle\Services\Security\UserProvider
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Usuario')"]
    consejo_authentication_provider:
        class:     AppBundle\Services\Security\AuthenticationProvider
        arguments: ["@security.password_encoder"]
    impresion_servicio:
        class: AppBundle\Services\ImpresionServicio
        arguments: ["@doctrine.orm.entity_manager","%kernel.root_dir%" ]
    utilidades_servicio:
        class: AppBundle\Services\UtilServicio
        #arguments: ["@doctrine.orm.entity_manager"]
